var namespace_biller_1_1_u_i_1_1_settings_view_1_1_settings_list_1_1_shipment_settings =
[
    [ "ShipmentTabContent", "class_biller_1_1_u_i_1_1_settings_view_1_1_settings_list_1_1_shipment_settings_1_1_shipment_tab_content.html", "class_biller_1_1_u_i_1_1_settings_view_1_1_settings_list_1_1_shipment_settings_1_1_shipment_tab_content" ],
    [ "ShipmentTabItem", "class_biller_1_1_u_i_1_1_settings_view_1_1_settings_list_1_1_shipment_settings_1_1_shipment_tab_item.html", "class_biller_1_1_u_i_1_1_settings_view_1_1_settings_list_1_1_shipment_settings_1_1_shipment_tab_item" ]
];